### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by vtiggrmsvj** [stupergenius/swift-heroku-slack-command#1]
Getting a build error, any idea how to resolve?

```
➜  swift-heroku-slack-command git:(master) swift build --configuration release
swift-build: Your source structure is not supported due to conflicting directories: /Users/cruffenach/Desktop/swift-heroku-slack-command/Packages/Curassow-0.2.0
```

**Comment by stupergenius** [comment]
Yes @vtiggrmsvj, the issue is upstream to due Curassow not building with the 12-18 snapshot release of Swift. If you downgrade to the 12-01 snapshot release for now, it will work until Curassow cuts another release. They've actually already fixed this, but they need to bump the version from 0.2 in order for us to target it. Below is the issue they've already addressed:
https://github.com/kylef/Curassow/issues/14

I'm adding a note to the blog post and the README to let others know this is currently an issue.

Thanks for the report!
